export const iconBaseStyle = {
  width: '3vh',
  height: '3vh',
  backgroundSize: 'contain',
  backgroundRepeat: 'no-repeat',
  WebkitMaskSize: 'contain',
  maskSize: 'contain',
  WebkitMaskRepeat: 'no-repeat',
  maskRepeat: 'no-repeat',
  display: 'inline-block',
};

export const iconVariants = {
  about: { WebkitMaskImage: "url('/icons/user.svg')", maskImage: "url('/icons/user.svg')" },
  skills: { WebkitMaskImage: "url('/icons/tools.svg')", maskImage: "url('/icons/tools.svg')" },
  projects: { WebkitMaskImage: "url('/icons/folder.svg')", maskImage: "url('/icons/folder.svg')" },
  contact: { WebkitMaskImage: "url('/icons/envelope.svg')", maskImage: "url('/icons/envelope.svg')" },
  'window-icon': { WebkitMaskImage: "url('/icons/window_icon.svg')", maskImage: "url('/icons/window_icon.svg')" },
  minimize: { WebkitMaskImage: "url('/icons/minus.svg')", maskImage: "url('/icons/minus.svg')" },
  maximize: { WebkitMaskImage: "url('/icons/arrows_pointing_out.svg')", maskImage: "url('/icons/arrows_pointing_out.svg')" },
  restore: { WebkitMaskImage: "url('/icons/arrows_pointing_in.svg')", maskImage: "url('/icons/arrows_pointing_in.svg')" },
  close: { WebkitMaskImage: "url('/icons/not_icon.svg')", maskImage: "url('/icons/not_icon.svg')" },
  sort: { WebkitMaskImage: "url('/icons/sort.svg')", maskImage: "url('/icons/sort.svg')" },
  refresh: { WebkitMaskImage: "url('/icons/refresh.svg')", maskImage: "url('/icons/refresh.svg')" },
  new: { WebkitMaskImage: "url('/icons/new.svg')", maskImage: "url('/icons/new.svg')" },
  download: { WebkitMaskImage: "url('/icons/arrow_down_tray.svg')", maskImage: "url('/icons/arrow_down_tray.svg')" },
  resize: { WebkitMaskImage: "url('/icons/resize_corner.svg')", maskImage: "url('/icons/resize_corner.svg')" },
  view: { WebkitMaskImage: "url('/icons/squares.svg')", maskImage: "url('/icons/squares.svg')" },
  'plus-circle': { WebkitMaskImage: "url('/icons/plus_circle.svg')", maskImage: "url('/icons/plus_circle.svg')" },
  'new-file': { WebkitMaskImage: "url('/icons/new_file.svg')", maskImage: "url('/icons/new_file.svg')" },
  search: { WebkitMaskImage: "url('/icons/magnify_glass.svg')", maskImage: "url('/icons/magnify_glass.svg')" },
  paint: { WebkitMaskImage: "url('/icons/paint_brush_solid.svg')", maskImage: "url('/icons/paint_brush_solid.svg')" },
  'color-picker': { WebkitMaskImage: "url('/icons/dropper.svg')", maskImage: "url('/icons/dropper.svg')" },
  command: { WebkitMaskImage: "url('/icons/cmd.svg')", maskImage: "url('/icons/cmd.svg')" },
  'task-manager': { WebkitMaskImage: "url('/icons/gear.svg')", maskImage: "url('/icons/gear.svg')" },
  browser: { WebkitMaskImage: "url('/icons/globe.svg')", maskImage: "url('/icons/globe.svg')" },
  'arrow-left': { WebkitMaskImage: "url('/icons/chevron_left.svg')", maskImage: "url('/icons/chevron_left.svg')" },
  'arrow-right': { WebkitMaskImage: "url('/icons/chevron_right.svg')", maskImage: "url('/icons/chevron_right.svg')" },
  'arrow-up': { WebkitMaskImage: "url('/icons/chevron_up.svg')", maskImage: "url('/icons/chevron_up.svg')" },
  'arrow-down': { WebkitMaskImage: "url('/icons/chevron_down.svg')", maskImage: "url('/icons/chevron_down.svg')" },
  github: { WebkitMaskImage: "url('/icons/github-mark.svg')", maskImage: "url('/icons/github-mark.svg')" },
  linkedin: { WebkitMaskImage: "url('/icons/linkedin.svg')", maskImage: "url('/icons/linkedin.svg')" },
};
